$('#Elya').typeIt({
     speed: 75,
     autoStart: false
})
.tiType('Эля ')
.tiPause(3000)
.tiSettings({speed: 150})
.tiType('Кекс?')
.tiPause(1500)
.tiDelete(5)
.tiPause(500)

.tiSettings({speed: 75})
.tiType('Факс?')
.tiPause(750)
.tiSettings({speed: 700})
.tiDelete(5)
.tiPause(300)
.tiSettings({speed: 100})
.tiType('Фикс?')
.tiPause(1000)
.tiDelete(5)
.tiPause(500)
.tiType('Микс?')
.tiPause(1250)
.tiDelete(5)
.tiPause(500)
.tiSettings({speed: 200})
.tiType('Fuck?')
.tiPause(1250)
.tiDelete(5)
.tiPause(500)
.tiSettings({speed: 300})
.tiType('Фуг')
.tiPause(350)
.tiDelete(7)
.tiSettings({speed: 75})
.tiPause(250)
.tiType('Да блять...')
.tiPause(1300)
.tiDelete(11)
.tiPause(500)
.tiSettings({speed: 100})
.tiType('Эля Фукс!')
.tiPause(1000)
.tiSettings({speed: 100})
.tiDelete(12)
.tiPause(100)
.tiType('Дорогая Эля!')
.tiPause(100)
.tiBreak()
.tiBreak()
.tiSettings({speed: 100})
.tiPause(600)
.tiType('Чёрт, тебе уже 17 годиков...')
.tiPause(300)
.tiBreak()
.tiType('Через год можно бухать официально! ')
.tiPause(300)
.tiType('А, не. ')
.tiPause(300)
.tiType('Только в 21 год:)')
.tiPause(300)
.tiBreak()
.tiType('А вообще, все равно сколько тебе лет.')
.tiPause(300)
.tiBreak()
.tiType('Пока ты еще не забеременела...😏 получай от жизни всё:)')

